import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from kamvas_bridge.hyprland import (
    HyprlandError,
    STYLUS_DEVICE_NAME,
    configure_hyprland,
    hyprland_status,
    remove_hyprland_config,
    render_hyprland_fragment,
)


class HyprlandConfigurationTests(unittest.TestCase):
    def test_renders_confirmed_lua_stylus_mapping(self) -> None:
        fragment = render_hyprland_fragment("HDMI-A-1")

        self.assertIn("hl.device({", fragment)
        self.assertIn(f'name = "{STYLUS_DEVICE_NAME}"', fragment)
        self.assertIn('output = "HDMI-A-1"', fragment)
        self.assertNotIn("tablet_gs1333-pen", fragment)

    def test_configure_is_idempotent_and_preserves_main_config(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            main = Path(directory) / "hyprland.lua"
            main.write_text("hl.config({ autogenerated = false })\n", encoding="utf-8")
            with (
                patch(
                    "kamvas_bridge.hyprland.hyprland_monitors",
                    return_value={"eDP-1", "HDMI-A-1"},
                ),
                patch("kamvas_bridge.hyprland._run_hyprctl"),
            ):
                first = configure_hyprland("HDMI-A-1", main_config=main)
                second = configure_hyprland("HDMI-A-1", main_config=main)

            text = main.read_text(encoding="utf-8")
            self.assertEqual(first, second)
            self.assertIn("hl.config({ autogenerated = false })", text)
            self.assertEqual(text.count("BEGIN kamvas-bridge"), 1)
            self.assertIn('pcall(require, "kamvas_bridge")', text)
            self.assertIn('output = "HDMI-A-1"', first.fragment.read_text())

    def test_reconfigure_changes_only_managed_output(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            main = Path(directory) / "hyprland.lua"
            main.write_text("-- personal config\n", encoding="utf-8")
            with (
                patch(
                    "kamvas_bridge.hyprland.hyprland_monitors",
                    return_value={"HDMI-A-1", "DP-2"},
                ),
                patch("kamvas_bridge.hyprland._run_hyprctl"),
            ):
                paths = configure_hyprland("HDMI-A-1", main_config=main)
                configure_hyprland("DP-2", main_config=main)

            self.assertIn('output = "DP-2"', paths.fragment.read_text())
            self.assertIn("-- personal config", main.read_text())

    def test_remove_deletes_only_managed_fragment_and_block(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            main = Path(directory) / "hyprland.lua"
            main.write_text("-- keep me\n", encoding="utf-8")
            with (
                patch(
                    "kamvas_bridge.hyprland.hyprland_monitors",
                    return_value={"HDMI-A-1"},
                ),
                patch("kamvas_bridge.hyprland._run_hyprctl"),
            ):
                paths = configure_hyprland("HDMI-A-1", main_config=main)
                remove_hyprland_config(main_config=main)

            self.assertEqual(main.read_text(encoding="utf-8"), "-- keep me\n")
            self.assertFalse(paths.fragment.exists())

    def test_legacy_config_gets_separate_source_fragment(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            main = Path(directory) / "hyprland.conf"
            main.write_text("$mod = SUPER\n", encoding="utf-8")
            with (
                patch("kamvas_bridge.hyprland.hyprland_monitors", return_value=set()),
                patch("kamvas_bridge.hyprland._run_hyprctl"),
            ):
                paths = configure_hyprland("HDMI-A-1", main_config=main)

            self.assertEqual(paths.syntax, "hyprlang")
            self.assertIn("source = ", main.read_text())
            self.assertIn("output = HDMI-A-1", paths.fragment.read_text())

    def test_rejects_unknown_active_output(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            main = Path(directory) / "hyprland.lua"
            main.touch()
            with (
                patch(
                    "kamvas_bridge.hyprland.hyprland_monitors",
                    return_value={"eDP-1"},
                ),
                self.assertRaisesRegex(HyprlandError, "not active"),
            ):
                configure_hyprland("HDMI-A-1", main_config=main)

    def test_status_is_not_an_error_without_hyprland(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            status = hyprland_status(home=Path(directory), environment={})

        self.assertFalse(status.detected)
        self.assertFalse(status.configured)
        self.assertIsNone(status.output_present)

    def test_status_verifies_configured_output_and_correct_stylus(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            main = Path(directory) / "hyprland.lua"
            main.write_text("-- personal\n", encoding="utf-8")
            with (
                patch(
                    "kamvas_bridge.hyprland.hyprland_monitors",
                    return_value={"HDMI-A-1"},
                ),
                patch("kamvas_bridge.hyprland._run_hyprctl"),
            ):
                configure_hyprland("HDMI-A-1", main_config=main)
            with (
                patch(
                    "kamvas_bridge.hyprland.hyprland_monitors",
                    return_value={"HDMI-A-1"},
                ),
                patch(
                    "kamvas_bridge.hyprland.hyprland_devices",
                    return_value={
                        "huion-huion-tablet_gs1333-pen",
                        STYLUS_DEVICE_NAME,
                    },
                ),
            ):
                status = hyprland_status(
                    main_config=main,
                    environment={"HYPRLAND_INSTANCE_SIGNATURE": "test"},
                )

        self.assertTrue(status.configured)
        self.assertEqual(status.output, "HDMI-A-1")
        self.assertTrue(status.output_present)
        self.assertTrue(status.stylus_present)


if __name__ == "__main__":
    unittest.main()
